name: CI

on:
  push:
    branches:
    - gh-actions
    - deauther

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    #- uses: actions/bin/curl@master
    #- name: Retrieve the zip from the archive using curl
    #  run: "https://github.com/tobozo/Arduino/archive/deauther.zip --output deauther.zip"
    #- uses: actions/bin/sha256sum@master
    #- uses: tobozo/Arduino@deauther
    - name: Run a multi-line script
      run: |
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/genpackage.php
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.ARM.tpl.json
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.tpl.json
        php genpackage.php 
        echo "Generated package_deauther_index.json :"
        cat package_deauther_index.json
        echo "Generated ARM package_deauther_index.json :"
        cat arm/package_deauther_index.json

