name: JSON Packages Generator

on:
  push:
    branches:
    - gh-actions
    - deauther

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Retrieve the packager tool
      run: |
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/genpackage.php
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.ARM.tpl.json
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.tpl.json
    - name: Use the tool to generate the json files
      run: |
        php genpackage.php
    - name: Print generated content
        echo "Generated package_deauther_index.json :"
        cat package_deauther_index.json
        echo "Generated ARM package_deauther_index.json :"
        cat arm/package_deauther_index.json

