name: JSON Packages Generator

on:
  push:
    branches:
    - gh-actions
    - deauther

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Packager
      run: |
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/genpackage.php
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.ARM.tpl.json
        wget https://raw.githubusercontent.com/tobozo/Arduino/deauther/.github/scripts/package_deauther_index.tpl.json
        php genpackage.php
        echo "Generated package_deauther_index.json :"
        cat package_deauther_index.json
        echo "Generated ARM package_deauther_index.json :"
        cat arm/package_deauther_index.json
        git clone https://github.com/tobozo/Arduino.wiki.git
        cp -R arm Arduino.wiki/
        cp arm/package_deauther_index.json Arduino.wiki/
        cd Arduino.wiki/
        git remote rm origin
        git remote add origin https://tobozo:${{ secrets.GITHUB_TOKEN }}@github.com/tobozo/Arduino.wiki.git
        git add .
        git status
        git commit -m "autocommit on wiki"
        git push -u origin master
