name: CI

on:
  push:
    branches:
    - gh-actions
    - deauther

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/bin/curl@master
    - name: Retrieve the zip from the archive using curl
      run: curl https://github.com/tobozo/Arduino/archive/deauther.zip --output deauther.zip
    - name: Run a multi-line script
      run: |
        #curl https://github.com/tobozo/Arduino/archive/deauther.zip --output deauther.zip
        export SHA_SUM=`sha256sum deauther.zip |cut -d' ' -f1`
        echo $SHA_SUM
        ls
        echo Add other actions to build,
        echo test, and deploy your project.
